In [60]:
import numpy as np

In [61]:
a = np.random.random((10,4))
print(a)

[[0.75069265 0.53100122 0.48637696 0.20811268]
 [0.28855746 0.86233589 0.82170344 0.64340505]
 [0.66165029 0.66529042 0.82118104 0.33245214]
 [0.23842237 0.99227012 0.70958494 0.78773342]
 [0.59956754 0.72311601 0.78621408 0.48428124]
 [0.77134511 0.90509481 0.39564717 0.70004292]
 [0.6590291  0.28677295 0.92953274 0.43896178]
 [0.22973736 0.96647811 0.51706048 0.11653039]
 [0.27601849 0.7595283  0.80449362 0.42240349]
 [0.61892953 0.31949189 0.83564542 0.43967919]]


In [64]:
print(a.shape)
print(a.size)

(10, 4)
40


In [65]:
b = np.random.random((5,2,3))
print(b)

[[[0.38209725 0.73130747 0.13139883]
  [0.54919881 0.62527461 0.06686365]]

 [[0.41784632 0.57334965 0.65472623]
  [0.10141847 0.93333435 0.76158615]]

 [[0.48849578 0.48209849 0.14422475]
  [0.17104929 0.33208798 0.34032683]]

 [[0.51688537 0.20437048 0.13783884]
  [0.56326734 0.48755547 0.79034624]]

 [[0.21316809 0.70613788 0.28755579]
  [0.78208943 0.27986811 0.44478567]]]


In [66]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.44663079 0.45587552 0.34027188 0.87870477 0.93915403]
   [0.55978169 0.81853125 0.782765   0.30755853 0.74114237]
   [0.04763072 0.70659481 0.23311463 0.02229541 0.83197282]
   [0.14375095 0.47215241 0.79180787 0.27993674 0.70350349]]

  [[0.3665001  0.86685626 0.65787738 0.67181739 0.70525825]
   [0.11123508 0.37934655 0.12405944 0.92505666 0.76646772]
   [0.12351937 0.93124277 0.73067305 0.26628257 0.78452375]
   [0.08914688 0.99100968 0.17017203 0.1999631  0.65197426]]

  [[0.60723534 0.91786533 0.35927988 0.83349414 0.22244334]
   [0.30643961 0.75649524 0.03756907 0.83671041 0.16471386]
   [0.20445988 0.44138606 0.41151599 0.70515164 0.89430329]
   [0.41987159 0.40370205 0.4042362  0.14056436 0.28353539]]]


 [[[0.8194405  0.11574288 0.80283331 0.13397416 0.96340668]
   [0.91302462 0.04566511 0.09247761 0.55249625 0.1542715 ]
   [0.41580112 0.35890579 0.38807288 0.45471243 0.43333296]
   [0.94616899 0.73590145 0.87085776 0.83140426 0.58146401]]

  [[0.64534837 0.69299664 0.59

In [68]:
# First row of matrix a
print(a)
print(a[0])

[[0.75069265 0.53100122 0.48637696 0.20811268]
 [0.28855746 0.86233589 0.82170344 0.64340505]
 [0.66165029 0.66529042 0.82118104 0.33245214]
 [0.23842237 0.99227012 0.70958494 0.78773342]
 [0.59956754 0.72311601 0.78621408 0.48428124]
 [0.77134511 0.90509481 0.39564717 0.70004292]
 [0.6590291  0.28677295 0.92953274 0.43896178]
 [0.22973736 0.96647811 0.51706048 0.11653039]
 [0.27601849 0.7595283  0.80449362 0.42240349]
 [0.61892953 0.31949189 0.83564542 0.43967919]]
[0.75069265 0.53100122 0.48637696 0.20811268]


In [69]:
# First column of matrix a
print(a[:,0])

[0.75069265 0.28855746 0.66165029 0.23842237 0.59956754 0.77134511
 0.6590291  0.22973736 0.27601849 0.61892953]


In [70]:
# Value in the fifth row and third column of matrix a
print(a[4,2])

0.7862140808534376


In [75]:
xlist = [[0.75069265, 0.53100122, 0.48637696, 0.20811268],
 [0.28855746, 0.86233589, 0.82170344, 0.64340505],
 [0.66165029 ,0.66529042 ,0.82118104 ,0.33245214],
 [0.23842237, 0.99227012, 0.70958494, 0.78773342],
 [0.59956754 ,0.72311601 ,0.78621408 ,0.48428124],
 [0.77134511, 0.90509481, 0.39564717, 0.70004292],
 [0.6590291  ,0.28677295 ,0.92953274 ,0.43896178],
 [0.22973736, 0.96647811, 0.51706048, 0.11653039],
 [0.27601849 ,0.7595283  ,0.80449362 ,0.42240349],
 [0.61892953, 0.31949189, 0.83564542, 0.43967919]]
#third value in fifth sublist
xlist[4][2]


0.78621408

In [76]:
# First group of array c
print(c[0])

[[[0.44663079 0.45587552 0.34027188 0.87870477 0.93915403]
  [0.55978169 0.81853125 0.782765   0.30755853 0.74114237]
  [0.04763072 0.70659481 0.23311463 0.02229541 0.83197282]
  [0.14375095 0.47215241 0.79180787 0.27993674 0.70350349]]

 [[0.3665001  0.86685626 0.65787738 0.67181739 0.70525825]
  [0.11123508 0.37934655 0.12405944 0.92505666 0.76646772]
  [0.12351937 0.93124277 0.73067305 0.26628257 0.78452375]
  [0.08914688 0.99100968 0.17017203 0.1999631  0.65197426]]

 [[0.60723534 0.91786533 0.35927988 0.83349414 0.22244334]
  [0.30643961 0.75649524 0.03756907 0.83671041 0.16471386]
  [0.20445988 0.44138606 0.41151599 0.70515164 0.89430329]
  [0.41987159 0.40370205 0.4042362  0.14056436 0.28353539]]]


In [77]:
# Second subgroup of the first group
print(c[0,1])

[[0.3665001  0.86685626 0.65787738 0.67181739 0.70525825]
 [0.11123508 0.37934655 0.12405944 0.92505666 0.76646772]
 [0.12351937 0.93124277 0.73067305 0.26628257 0.78452375]
 [0.08914688 0.99100968 0.17017203 0.1999631  0.65197426]]


In [91]:
# Fourth column of the second subgroup
print(c[0,1,:,3])
#print(c[:,0])
print(list(c[0,1,:,3]))
newarr = np.array([0.6718173948698819, 0.9250566560295915, 0.2662825704884635, 0.19996310250953375])
print(newarr)
for i in newarr:
    print(i)

[0.67181739 0.92505666 0.26628257 0.1999631 ]
[0.6718173948698819, 0.9250566560295915, 0.2662825704884635, 0.19996310250953375]
[0.67181739 0.92505666 0.26628257 0.1999631 ]
0.6718173948698819
0.9250566560295915
0.2662825704884635
0.19996310250953375


In [92]:
# Value in the third row and fourth column of the second subgroup of the first group
print(c[0,1,2,3])

0.2662825704884635


In [93]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
# Sum of all elements in matrix a
print(np.sum(a))

45


In [96]:
# Sum of each column in matrix a
print(np.sum(a, axis=0))

[5.0939499  7.01137972 7.10743988 4.57360231]


In [97]:
# Sum of each row in matrix a
print(np.sum(a, axis=1))

[1.97618351 2.61600183 2.48057389 2.72801085 2.59317887 2.77213
 2.31429658 1.82980634 2.2624439  2.21374603]


In [98]:
# Sum of all the elements in the first two groups of array b
np.sum(b[:2])

5.9284017827958

In [100]:
# Mean of all elements in matrix a
print(np.mean(a))


23.7863718126987


In [101]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))

[0.50939499 0.70113797 0.71074399 0.45736023]


In [102]:
# Mean of each row in matrix a
print(np.mean(a, axis=1))

[0.49404588 0.65400046 0.62014347 0.68200271 0.64829472 0.6930325
 0.57857414 0.45745159 0.56561097 0.55343651]


In [103]:
# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

0.49403348189964996

In [104]:
x = c[0,0]
print(x)

[[0.44663079 0.45587552 0.34027188 0.87870477 0.93915403]
 [0.55978169 0.81853125 0.782765   0.30755853 0.74114237]
 [0.04763072 0.70659481 0.23311463 0.02229541 0.83197282]
 [0.14375095 0.47215241 0.79180787 0.27993674 0.70350349]]


In [105]:
y = c[0,1]
print(y)

[[0.3665001  0.86685626 0.65787738 0.67181739 0.70525825]
 [0.11123508 0.37934655 0.12405944 0.92505666 0.76646772]
 [0.12351937 0.93124277 0.73067305 0.26628257 0.78452375]
 [0.08914688 0.99100968 0.17017203 0.1999631  0.65197426]]


In [106]:
# Add elements of x and y together
print(np.add(x, y))

[[0.81313089 1.32273178 0.99814925 1.55052216 1.64441228]
 [0.67101677 1.19787779 0.90682444 1.23261519 1.50761009]
 [0.17115009 1.63783757 0.96378768 0.28857798 1.61649656]
 [0.23289783 1.46316209 0.9619799  0.47989985 1.35547775]]


In [107]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

[[-0.08013069  0.41098074  0.3176055  -0.20688737 -0.23389579]
 [-0.44854661 -0.4391847  -0.65870556  0.61749812  0.02532535]
 [ 0.07588866  0.22464796  0.49755842  0.24398716 -0.04744907]
 [-0.05460407  0.51885727 -0.62163585 -0.07997364 -0.05152923]]


In [108]:
# Multiply elements of x and y together
print(np.multiply(x, y))

[[0.16369023 0.39517855 0.22385717 0.59032915 0.66234613]
 [0.06226736 0.310507   0.09710939 0.28450907 0.5680617 ]
 [0.00588332 0.6580113  0.17033058 0.00593688 0.65270243]
 [0.01281495 0.46790761 0.13474355 0.05597702 0.45866617]]


In [109]:
# Divide elements of y by elements of x
print(np.divide(y, x))

[[ 0.82058851  1.90151965  1.93338744  0.76455417  0.75095056]
 [ 0.19871154  0.46344785  0.15848874  3.00774181  1.03417069]
 [ 2.59327145  1.31793039  3.13439382 11.94338168  0.942968  ]
 [ 0.6201481   2.09891902  0.2149158   0.71431531  0.92675341]]


In [110]:
%%time
for i in range(100000):
    z = np.multiply(x, y)

CPU times: user 65.2 ms, sys: 2.12 ms, total: 67.3 ms
Wall time: 66.5 ms


In [112]:
import random
x_list = [[random.random() for j in range(5)] for i in range(4)]
y_list = [[random.random() for j in range(5)] for i in range(4)]

In [113]:
%%time
for i in range(100000):
    z = []
    for i in range(4):
        innerlist = []
        for j in range(5):
            innerlist.append(x_list[i][j]*y_list[i][j])
        z.append(innerlist)

print(z)
    

[[0.26272400309758204, 0.08459852738972748, 0.06599827724289356, 0.07464754460906868, 0.2945765513324983], [0.38853234695592964, 0.4627130589581721, 0.3660061778336424, 0.021429392089002876, 0.10807031406473692], [0.5286299466842767, 0.14128465013956942, 0.07658141348995316, 0.48758680773363794, 0.2530539332039517], [0.016216285844986918, 0.15135248440270915, 0.3563239350646966, 0.15012921700880716, 0.24011820063047357]]
CPU times: user 754 ms, sys: 3.7 ms, total: 757 ms
Wall time: 757 ms


In [114]:
%%time
for i in range(100):
    x_new = [j for j in range(1000)]
    
#print(x)

CPU times: user 6.43 ms, sys: 315 µs, total: 6.74 ms
Wall time: 6.82 ms


In [115]:
%%time
for i in range(100):
    x = []
    for j in range(1000):
        x.append(j)
    
#print(x)

CPU times: user 17.6 ms, sys: 1.39 ms, total: 19 ms
Wall time: 17.9 ms
